import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider, useTranslations } from "next-intl";

import { SelectLocale } from "@/components/select-locale";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = useTranslations();

  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-background text-foreground antialiased`}
      >
        <script src="https://lds-img.finalfantasyxiv.com/pc/global/js/eorzeadb/loader.js?v3"></script>
        <header className="sticky top-0 z-20 w-full bg-background/90 backdrop-blur supports-backdrop-filter:bg-background/70">
          <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4">
            <h1 className="font-bold">{t("title")}</h1>
            <SelectLocale />
          </div>
        </header>
        <NextIntlClientProvider>
          <main className="mx-auto w-full max-w-7xl px-4 pt-6 pb-8">
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
